name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
     services: 
      mysql:
          image: mysql:5.7.22
          ports:
              - 33060:3306
          env:
              - MYSQL_DATABASE=db_golang_architecture
              - MYSQL_USER=root
              - MYSQL_PASSWORD=
              - MYSQL_ROOT_PASSWORD=root
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: run docker
      run: docker-compose up -d

    - name: Test
      run: |
         make integration-test
   

    # - name: Test
    #   run: go test -v ./...
